<?php


namespace Diemayrei\CoverImageImport\Console\Command;

use Magento\Framework\App\ObjectManager;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportCover extends Command
{
    /** @var Magento\Framework\App\State  */
    protected $appState;

    /**
     */
    public function __construct(
        \Magento\Framework\App\State $appState
    ) {
        $this->appState = $appState;
        parent::__construct();
    }


    protected function configure()
    {
        $this->setName('diemayrei:CoverImageImport');
        $this->setDescription('Update all cover Images and clear specific caches');

        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_CRONTAB);
        $cronQueueWorker = ObjectManager::getInstance()->get('Diemayrei\CoverImageImport\Cron\FetchCover');
        $cronQueueWorker->execute();

        return \Magento\Framework\Console\Cli::RETURN_SUCCESS;
    }
}
