<?php
/**
 * @var DieMayrei\EmailNotice\Block\Display $block
 */

$_order_id = $block->getData('order_id');
$notes = $block->getNotes($_order_id);
$redirects = $block->getRedirects($_order_id);
?>
<tr>
    <td>
        <?php if (count($notes)): ?>
            <div style="padding: 15px 0px;">
                <p style="font-weight: bold;">Wichtige Informationen zu Ihrer Bestellung:</p>
                <?php foreach ($notes as $note): ?>
                    <div style="background-color: #d4edda; padding: .75rem 1.25rem; border: 1px solid #c3e6cb; color: #155724; margin-bottom: 10px">
                        <?= $escaper->escapeHtml($note) ?>
                    </div>
                <?php endforeach; ?>
                <?php foreach ($redirects as $redirect): ?>
                    <?= $escaper->escapeHtml($redirect) ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </td>
</tr>
