<?php

/**
 * Customer service teaser for the footer.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<div class="flex flex-col justify-between w-full">
    <div>
        <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">
            <?= $escaper->escapeHtml(__('Unser Kundenservice')) ?>
        </h2>
        <p class="mt-4 text-sm text-gray-700">
            <?= $escaper->escapeHtml(
                __('Sie haben noch Fragen? Unser Kundenservice hilft telefonisch oder per E-Mail weiter.')
            ) ?>
        </p>
        <p class="mt-2 text-sm text-gray-700">
            <?= $escaper->escapeHtml(__('Sie erreichen uns während unserer Geschäftszeiten von:')) ?>
            <span class="mt-2 font-semibold text-sm text-gray-900">
                <?= $escaper->escapeHtml(__('Montag – Freitag: 07:30 – 19:00 Uhr')) ?>
            </span>
        </p>
    </div>
    <div class="mt-6 grid grid-cols-1 gap-2 md:grid-cols-2">
        <a href="/kundenservice" class="md:col-span-2 p-2 w-full flex items-center justify-center gap-2 text-center text-white font-semibold text-xs tracking-wide uppercase py-3 rounded-lg bg-primary hover:bg-primary-lighter transition duration-300 ease-in-out">
            <i class="bi bi-person-vcard-fill text-xl leading-none" aria-hidden="true"></i>
            <?= $escaper->escapeHtml(__('Übersicht')) ?>
        </a>
        <a href="tel:+493029397447" class="p-2 w-full flex items-center justify-center gap-2 text-center text-white font-semibold text-xs tracking-wide uppercase py-3 rounded-lg bg-secondary hover:bg-secondary-lighter transition duration-300 ease-in-out">
            <i class="bi bi-telephone-fill text-xl leading-none" aria-hidden="true"></i>
            <?= $escaper->escapeHtml(__('+49 30 293974-47')) ?>
        </a>
        <a href="mailto:#" class="p-2 w-full flex items-center justify-center gap-2 text-center text-white font-semibold text-xs tracking-wide uppercase py-3 rounded-lg bg-secondary hover:bg-secondary-lighter transition duration-300 ease-in-out">
            <i class="bi bi-envelope-at-fill text-xl leading-none" aria-hidden="true"></i>
            <?= $escaper->escapeHtml(__('kundenservice@hk-verlag.de')) ?>
        </a>
    </div>
</div>