<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);
?>

<?php
$heros = [
    [
        'image' => 'images/hero/gefluegelzeitung.jpg',
        'alt' => 'Geflügelzeitung',
        'link' => '/gefluegelzeitung',
    ],
    [
        'image' => 'images/hero/kaninchenzeitung.jpg',
        'alt' => 'Kaninchenzeitung',
        'link' => '/kaninchenzeitung',
    ]
];
?>

<section class="mb-24 lg:mt-6 grid grid-cols-1 md:grid-cols-2 gap-8" aria-labelledby="page-title">
    <?php foreach ($heros as $hero): ?>
        <div class="card card-interactive overflow-hidden p-0">
            <a href="<?= $escaper->escapeHtmlAttr($hero['link']) ?>" class="block group">
                <img
                    src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl($hero['image'])) ?>"
                    alt="<?= $escaper->escapeHtmlAttr($hero['alt']) ?>"
                    class="w-full h-auto">
            </a>
        </div>
    <?php endforeach; ?>
</section>

<?php $hyvaCsp->registerInlineScript() ?>